#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["identifier=back;size=1", "identifier=backpack;size=1", "identifier=cape;size=1"]

