
# Let's Configure Delightful
[Knives]
	adamantium_knife = false
	alf_knife = false
	allthemodium_knife = false
	aluminum_knife = false
	amethyst_knife = false
	black_opal_knife = false
	blazing_knife = false
	bone_knife = false
	brass_knife = false
	bronze_knife = false
	certus_quartz_knife = false
	cloggrum_knife = false
	constantan_knife = false
	copper_knife = false
	crystalline_knife = false
	draco_arcanus_knife = false
	electrum_knife = false
	elementium_knife = false
	emerald_knife = false
	enderite_knife = false
	experience_knife = false
	fiery_knife = false
	fluix_knife = false
	forgotten_knife = false
	froststeel_knife = false
	gilded_netherite_knife = false
	gilded_quartz_knife = false
	gravitite_knife = false
	holystone_knife = false
	infused_veridium_knife = false
	invar_knife = false
	ironwood_knife = false
	kiwano_knife = false
	knightmetal_knife = false
	lapis_lazuli_knife = false
	large_amethyst_knife = false
	lead_knife = false
	leaf_knife = false
	living_knife = false
	manasteel_knife = false
	mythril_knife = false
	necronium_knife = false
	nether_quartz_knife = false
	netherite_opal_knife = false
	nickel_knife = false
	obsidian_infused_enderite_knife = false
	onyx_knife = false
	osmium_knife = false
	pearlescent_knife = false
	phoenix_knife = false
	refined_glowstone_knife = false
	refined_obsidian_knife = false
	resonarium_knife = false
	rose_gold_knife = false
	silver_knife = false
	sinisite_knife = false
	skyjade_knife = false
	skyroot_knife = false
	soul_steel_knife = false
	steel_knife = false
	steeleaf_knife = false
	stratus_knife = false
	terra_knife = false
	thyrium_knife = false
	tin_knife = false
	utherium_knife = false
	valkyrum_knife = false
	veridium_knife = false
	warden_knife = false
	zanite_knife = false
	zinc_knife = false

["Baked Good Overhauls"]
	blueberry_pie_slice = true
	chorus_pie_slice = false
	gloomgourd_pie_slice = true
	green_apple_pie_slice = true
	mulberry_pie_slice = true
	mutton_pie_slice = true
	passion_fruit_tart_slice = true
	pumpkin_pie_slice = true
	source_berry_pie_slice = false

["Registry & Recipes"]
	acorn = true
	acorn_sack = true
	aged_fish_roe = true
	aged_prawn_roe = true
	animal_fat = true
	animal_oil_bottle = true
	azalea_tea = true
	baklava = true
	baklava_slice = true
	baobab_fruit_crate = false
	basalt_cabinet = true
	bastion_fruit_crate = false
	berry_matcha_latte = true
	blueberry_sack = true
	bombegranate_crate = false
	cactus_chili = true
	cactus_flesh = true
	cactus_soup = true
	cactus_soup_cup = true
	cactus_steak = true
	cantaloupe = true
	cantaloupe_bread = true
	cantaloupe_gummy = false
	cantaloupe_popsicle = true
	cantaloupe_seeds = true
	cantaloupe_slice = true
	cheeseburger = true
	chopped_clover = true
	chorus_muffin = true
	chunkwich = true
	coconut_curry = true
	cooked_goat = true
	cooked_marshmallow_stick = true
	cooked_venison_chops = true
	crab_rangoon = true
	deluxe_cheeseburger = true
	ender_nectar = true
	field_salad = true
	frostaya_crate = false
	glow_jam_cookie = true
	glow_jam_cookie_tile_slab = true
	glow_jam_cookie_tile_stairs = true
	glow_jam_cookie_tile_wall = true
	glow_jam_cookie_tiles = true
	glow_jam_jar = true
	green_apple_crate = false
	green_tea_leaf = true
	honey_glazed_walnut = true
	jam_jar = true
	lavender_tea = true
	long_prickly_pear_juice = true
	marshmallow_stick = true
	matcha = true
	matcha_gummy = false
	matcha_ice_cream = true
	matcha_ice_cream_block = false
	matcha_latte = true
	matcha_milkshake = true
	mendosteen_crate = false
	mini_melon = true
	nut_butter_and_jam_sandwich = true
	nut_butter_bottle = true
	nut_dough = true
	prickly_pear_juice = true
	quartz_cabinet = true
	raw_goat = true
	roasted_acorn = true
	rock_candy = false
	roe_blini = true
	salmon_and_roe_blini = true
	salmonberries = true
	salmonberry_gummy = false
	salmonberry_ice_cream = true
	salmonberry_ice_cream_block = false
	salmonberry_milkshake = true
	salmonberry_pie = true
	salmonberry_pie_slice = true
	salmonberry_pips = true
	salmonberry_sack = true
	sinigang = true
	sinigang_cup = true
	smore = true
	source_berry_cookie = true
	source_berry_cookie_tile_slab = true
	source_berry_cookie_tile_stairs = true
	source_berry_cookie_tile_wall = true
	source_berry_cookie_tiles = true
	source_berry_gummy = false
	source_berry_ice_cream = true
	source_berry_ice_cream_block = false
	source_berry_milkshake = true
	stuffed_cantaloupe = true
	stuffed_cantaloupe_block = true
	venison_chops = true
	venison_stew = true
	venison_stew_cup = true
	wild_salmonberries = true
	wrapped_cantaloupe = true
	yucca_fruit_crate = false
	#Allow cooking milk from nuts
	nut_milk = true
	#Allow cooking honey from honey and clovers
	clover_honey = false
	#Give items that are sliced off of blocks directly to player's inventory instead of dropping
	give_sliced_directly = false
	#Allow sliced melons to be juiced in-world (right click)
	melon_juicing = true

