
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.deeperdarker]
			bloom = true
			echo = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.dungeonnowloading]
			azuro_oak = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.valhelsia_structures]
			lapidified_jungle = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.ender_remastered]
			deep = true

		[types.wood_type.minecraft]
			pale_oak = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.vinery]
			dark_cherry = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

	[types.cake]

		[types.cake.farmersrespite]
			coffee_cake = true

	[types.leaves_type]

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.dungeonnowloading]
			azuro = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			snowblossom = true
			rainbow_birch = true
			yellow_autumn = true
			orange_autumn = true
			maple = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.minecraft]
			pale_oak = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.villagersplus]
			horticulturist_table = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.valhelsia_structures]
			bundled_stripped_posts = true
			stripped_post = true
			cut_post = true
			bundled_posts = true
			post = true
			cut_stripped_post = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.valhelsia_furniture]
			table = true
			stool = true
			hay_chair = true
			chair = true
			desk_drawer = true
			desk = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			vertical_slab = true

		[entries.wood_type.hearth_and_home]
			lattice = true
			parquet = true
			vertical_trim = true
			trim = true
			sanded_wood = true

		[entries.wood_type.backpacked]
			backpack_shelf = true

		[entries.wood_type.mcwroofs]
			planks_upper_steep_roof = true
			top_roof = true
			lower_roof = true
			planks_roof = true
			upper_steep_roof = true
			steep_roof = true
			roof = true
			planks_attic_roof = true
			upper_lower_roof = true
			planks_top_roof = true
			planks_steep_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			planks_lower_roof = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true
			rope_bridge = true
			log_bridge_middle = true

		[entries.wood_type.mcwdoors]
			nether_door = true
			stable_head_door = true
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			cottage_door = true
			four_panel_door = true
			western_door = true
			paper_door = true
			bamboo_door = true
			swamp_door = true
			glass_door = true
			beach_door = true
			barn_door = true
			mystic_door = true
			whispering_door = true
			waffle_door = true
			japanese_door = true
			bark_glass_door = true
			classic_door = true
			stable_door = true
			modern_door = true

		[entries.wood_type.architects_palette]
			board_stairs = true
			railing = true
			boards = true
			board_slab = true
			board_wall = true

		[entries.wood_type.mcwwindows]
			plank_window = true
			louvered_shutter = true
			plank_window2 = true
			pane_window = true
			plank_pane_window = true
			stripped_pane_window = true
			plank_four_window = true
			stripped_log_window2 = true
			log_parapet = true
			window2 = true
			stripped_log_four_window = true
			four_window = true
			plank_parapet = true
			blinds = true
			window = true
			shutter = true
			stripped_log_window = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

